configurations:
  default-configuration:
    path: C:\Users\dmv31621\OneDrive - The Rosalind Franklin Institute\2024\00_Adaptive-milling\fibsem\fibsem\config\microscope-configuration.yaml
  microscope-configuration-demo2:
    path: C:\Users\dmv31621\OneDrive - The Rosalind Franklin Institute\2024\00_Adaptive-milling\fibsem\fibsem\config\microscope-configuration-demo2.yaml
default: microscope-configuration-demo2
