configurations:
  default-configuration:
    path: .\fibsem\fibsem\config\microscope-configuration.yaml
  microscope-configuration-demo2:
    path: .\fibsem\fibsem\config\microscope-configuration-demo2.yaml
default: microscope-configuration-demo2
